package com.felixawpw.indoormaps;

import android.content.Intent;
import android.graphics.Bitmap;
import android.provider.MediaStore;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.ImageView;
import android.widget.Toast;

import com.felixawpw.indoormaps.services.VolleyServices;
import com.felixawpw.indoormaps.util.ImageUtil;
import com.nostra13.universalimageloader.core.assist.FailReason;
import com.nostra13.universalimageloader.core.listener.ImageLoadingListener;

public class ScanPointDetailActivity extends AppCompatActivity {

    public static final String TAG = ScanPointDetailActivity.class.getSimpleName();
    int markerId;
    ImageView imageView;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_scan_point_detail);
        Intent intent = getIntent();
        markerId = Integer.parseInt(intent.getStringExtra("markerId"));
        Log.i(TAG, "Marker id = " + markerId);
        imageView = findViewById(R.id.activity_scan_point_detail_image_qrcode);
        ImageUtil.displayImage(imageView, VolleyServices.LOAD_MARKER_QR_CODE + markerId, new ImageLoadingListener() {
            @Override
            public void onLoadingStarted(String s, View view) {

            }

            @Override
            public void onLoadingFailed(String s, View view, FailReason failReason) {

            }

            @Override
            public void onLoadingComplete(String s, View view, Bitmap bitmap) {
                MediaStore.Images.Media.insertImage(getContentResolver(), bitmap, "indoornav_scanpoint_" + markerId  , "This QR code was generated by Indoor Nav App.");
                Toast.makeText(ScanPointDetailActivity.this, "QR Code is saved as indoornav_scanpoint_" + markerId, Toast.LENGTH_LONG).show();
                finish();
            }

            @Override
            public void onLoadingCancelled(String s, View view) {

            }
        });

    }
}
